<?php

declare(strict_types=1);

namespace Maetva\Chronopost\Endpoint\ShippingServiceWS;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'shipperValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShipperValue',
            'resultFaisabiliteESD' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultFaisabiliteESD',
            'esdValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\EsdValue',
            'headerValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\HeaderValue',
            'customerValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\CustomerValue',
            'recipientValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RecipientValue',
            'refValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RefValue',
            'skybillValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillValue',
            'skybillParamsValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillParamsValue',
            'resultExpeditionValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultExpeditionValue',
            'resultGetReservedSkybillWithTypeValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultGetReservedSkybillWithTypeValue',
            'donneurDOrdre' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\DonneurDOrdre',
            'adresseEnlevement' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AdresseEnlevement',
            'adresseEnlevementV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AdresseEnlevementV2',
            'adresseEnlevementV3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AdresseEnlevementV3',
            'particularitesEsd' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ParticularitesEsd',
            'options' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Options',
            'resultEnlevementNational' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultEnlevementNational',
            'infoEnlevement' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\InfoEnlevement',
            'scheduledValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ScheduledValue',
            'appointmentValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AppointmentValue',
            'esdWithRefClientValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\EsdWithRefClientValue',
            'esdWithRefClientValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\EsdWithRefClientValueV2',
            'resultReservationExpeditionValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultReservationExpeditionValue',
            'esdValue3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\EsdValue3',
            'skybillWithDimensionsValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillWithDimensionsValue',
            'skybillWithDimensionsValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillWithDimensionsValueV2',
            'skybillWithDimensionsValueV3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillWithDimensionsValueV3',
            'skybillParamsValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillParamsValueV2',
            'resultShippingValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultShippingValue',
            'resultMultiParcelExpeditionValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultMultiParcelExpeditionValue',
            'resultMultiParcelValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultMultiParcelValue',
            'skybillValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillValueV2',
            'resultReservationExpeditionValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultReservationExpeditionValueV2',
            'resultGetReservedSkybillValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultGetReservedSkybillValue',
            'resultReservationMultiParcelExpeditionValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultReservationMultiParcelExpeditionValue',
            'resultParcelValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultParcelValue',
            'shipperValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShipperValueV2',
            'recipientValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RecipientValueV2',
            'refValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RefValueV2',
            'skybillWithDimensionsValueV4' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillWithDimensionsValueV4',
            'skybillWithDimensionsValueV5' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillWithDimensionsValueV5',
            'skybillWithDimensionsValueV6' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillWithDimensionsValueV6',
            'recipientLocalValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RecipientLocalValue',
            'recipientLocalValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RecipientLocalValueV2',
            'customsValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\CustomsValue',
            'articleValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ArticleValue',
            'headerValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\HeaderValueV2',
            'resultReservationMultiParcelExpeditionValueV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultReservationMultiParcelExpeditionValueV2',
            'resultExpeditionValueV3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultExpeditionValueV3',
            'resultMonoParcelExpeditionValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultMonoParcelExpeditionValue',
            'esdResultContraintesAgenceValue' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\EsdResultContraintesAgenceValue',
            'esdContraintesAgence' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\EsdContraintesAgence',
            'resultAnnulerEnlevement' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultAnnulerEnlevement',
            'statut' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Statut',
            'entry' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Entry',
            'destinatairesDpd' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\DestinatairesDpd',
            'destinataireDpd' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\DestinataireDpd',
            'adresseDestinataire' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AdresseDestinataire',
            'infoClient' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\InfoClient',
            'particularites' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Particularites',
            'particularitesColisDpd' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ParticularitesColisDpd',
            'infoDouanieres' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\InfoDouanieres',
            'resultPickupOrCollectionRequest' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultPickupOrCollectionRequest',
            'skybillValueBase' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\SkybillValueBase',
            'resultShippingInfo' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultShippingInfo',
            'error' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Error',
            'detail' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Detail',
            'shippingInfo' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingInfo',
            'resultGetRouting' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ResultGetRouting',
            'geopostResult' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GeopostResult',
            'faisabiliteESD' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\FaisabiliteESD',
            'faisabiliteESDResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\FaisabiliteESDResponse',
            'shippingV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV2',
            'shippingV2Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV2Response',
            'getReservedSkybillWithTypeAndModeAuth' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeAndModeAuth',
            'getReservedSkybillWithTypeAndModeAuthResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeAndModeAuthResponse',
            'getReservedSkybillWithType' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithType',
            'getReservedSkybillWithTypeResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeResponse',
            'creerEnlevementNational' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\CreerEnlevementNational',
            'creerEnlevementNationalResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\CreerEnlevementNationalResponse',
            'shippingV3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV3',
            'shippingV3Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV3Response',
            'getReservedSkybillWithTypeAndModeByReservation' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeAndModeByReservation',
            'getReservedSkybillWithTypeAndModeByReservationResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeAndModeByReservationResponse',
            'shippingWithESDOnlyV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithESDOnlyV2',
            'shippingWithESDOnlyV2Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithESDOnlyV2Response',
            'shippingMultiParcel' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcel',
            'shippingMultiParcelResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelResponse',
            'shippingWithReservationV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationV2',
            'shippingWithReservationV2Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationV2Response',
            'shipping' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\Shipping',
            'shippingResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingResponse',
            'getReservedSkybill' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybill',
            'getReservedSkybillResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillResponse',
            'shippingMultiParcelWithReservation' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelWithReservation',
            'shippingMultiParcelWithReservationResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelWithReservationResponse',
            'shippingMultiParcelV4' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV4',
            'shippingMultiParcelV4Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV4Response',
            'shippingMultiParcelV5' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV5',
            'shippingMultiParcelV5Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV5Response',
            'shippingMultiParcelWithReservationV3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelWithReservationV3',
            'shippingMultiParcelWithReservationV3Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelWithReservationV3Response',
            'shippingMultiParcelV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV2',
            'shippingMultiParcelV2Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV2Response',
            'shippingV6' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV6',
            'shippingV6Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV6Response',
            'shippingWithReservation' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservation',
            'shippingWithReservationResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationResponse',
            'shippingV7' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV7',
            'shippingV7Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV7Response',
            'rechercherContraintesEnlevement' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RechercherContraintesEnlevement',
            'rechercherContraintesEnlevementResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\RechercherContraintesEnlevementResponse',
            'annulerEnlevements' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AnnulerEnlevements',
            'annulerEnlevementsResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\AnnulerEnlevementsResponse',
            'creerEnlevementEurope' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\CreerEnlevementEurope',
            'creerEnlevementEuropeResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\CreerEnlevementEuropeResponse',
            'shippingWithReservationAndESDWithRefClient' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationAndESDWithRefClient',
            'shippingWithReservationAndESDWithRefClientResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationAndESDWithRefClientResponse',
            'getReservedSkybillWithTypeAndMode' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeAndMode',
            'getReservedSkybillWithTypeAndModeResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetReservedSkybillWithTypeAndModeResponse',
            'shippingV4' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV4',
            'shippingV4Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV4Response',
            'shippingWithReservationAndESDWithRefClientPC' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationAndESDWithRefClientPC',
            'shippingWithReservationAndESDWithRefClientPCResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithReservationAndESDWithRefClientPCResponse',
            'shippingV5' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV5',
            'shippingV5Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingV5Response',
            'shippingMultiParcelWithReservationV2' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelWithReservationV2',
            'shippingMultiParcelWithReservationV2Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelWithReservationV2Response',
            'shippingWithESDOnly' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithESDOnly',
            'shippingWithESDOnlyResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingWithESDOnlyResponse',
            'getShippingInformation' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetShippingInformation',
            'getShippingInformationResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetShippingInformationResponse',
            'getRouting' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetRouting',
            'getRoutingResponse' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\GetRoutingResponse',
            'shippingMultiParcelV3' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV3',
            'shippingMultiParcelV3Response' => '\\Drupal\\commerce_chronopost\\Endpoint\\ShippingServiceWS\\StructType\\ShippingMultiParcelV3Response',
        ];
    }
}
